PROJECT           := esp8266test
DEVICES           := LPC1768
GCC4MBED_DIR      := ../../gcc4mbed
NO_FLOAT_SCANF    := 1
NO_FLOAT_PRINTF   := 1
GCC4MBED_TYPE     := Checked
MRI_BREAK_ON_INIT := 0
MRI_UART          := MRI_UART_MBED_P13_P14 MRI_UART_BAUD=460800
#MRI_UART          := MRI_UART_MBED_USB MRI_UART_BAUD=230400

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
